name: CI
on: [push, pull_request]

#env:

jobs:
  build:
    runs-on: ubuntu-latest
    # 大约用时 ? 分钟
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      # cache cargo
      - uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-1
      # rust 编译工具
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
      - run: cargo --version

      # # wasm-gc
      # - run: cargo install wasm-gc
      # - run: type wasm-gc

      # 主要编译过程 (检查, 测试, 编译)
      - run: cargo fmt --check
      - run: cargo test
      - run: cargo build --release

      # 上传编译结果
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: libvreui.rlib
          path: target/release/libvreui.rlib
